### ISSUE TITLE
Observability

### ISSUE THREAD

**Issue by roel4ez** [EliiseS/EliiseS#1]
## Overview

Understand and implement e2e visibility of an AliceSprings deployment and any applications running on top of it

## Prerequisites

- Alice Springs instance up and running, with OEE tutorial
- Azure Monitor instance available

## Tasks

- [ ] Setup Alice Springs
- [ ] Setup Azure Monitor and connect with Arc AKS
- [ ] Follow OEE tutorial
- [ ] Implement observability steps
